### ISSUE TITLE
dotCover analyse with tests lead to System.IO.FileNotFoundException: 'PresentationCore, Version=4.0.0.0'

### ISSUE THREAD

**Issue by Prodigio** [nuke-build/nuke#645] opened 2021-01-13 12:49 UTC
### Description

With the help of NUKE we run dotCover to analyse in combination with NUnit - which executes our tests - to analyse our code coverage.

So a raw command could look something like this:
```
.\dotCover.exe analyse
--ReportType=Html
--Output=D:\output\CodeCoverage\Report.dotCover.html
--TargetExecutable=C:\Users\<user>\NUnit.Console-3.12.0-beta1\bin\netcoreapp3.1\nunit3-console.exe
--TargetArguments="<list of test dlls>"
--InheritConsole=True
--AnalyseTargetArguments=True
--Filters="<list of modules and methods to ignore>"
```

Some of our tests need the "`PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`" assembly to be loaded.

So when executing the `Build.ps1 UnitTest` script, some tests fail with the exception:
```
System.IO.FileNotFoundException : Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

My conculsion was, that's because the compiled build.exe, which NUKE generates, is not referencing the WPF framework, so no `PresentationCore` was loaded.

### Steps to reproduce

So I did two attempts:

1. `Assembly.Load(new AssemblyName("PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)");`

Here I'm trying to load the `PresentationCore` assembly from GAC.
Same `System.IO.FileNotFoundException` as mentioned above, when executing the raw command.

2. Changing the NUKE build project in our solution to the following via `.csproj` file, to reference the WPF framework

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <NoWarn>CS0649;CS0169;NU1701</NoWarn>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```

Which led to another exception:
```
System.IO.IOException: 'The handle is invalid.'
   at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
   at System.Console.set_OutputEncoding(Encoding value)
   at Nuke.Common.Execution.BuildManager.Execute[T](Expression`1[] defaultTargetExpressions)
   at Nuke.Common.NukeBuild.Execute[T](Expression`1[] defaultTargetExpressions)
   at Build.Main() in D:\<application>\src\_build\Build.cs:line 42
```

Which totally makes sense to me. The compiled application is a WPF application now, not a command line application.
So the following assignment to `Console.OutputEncoding` will fail:

https://github.com/nuke-build/nuke/blob/4ce4af8a829d9a9a3fe915340ff30fe454671c1f/source/Nuke.Common/Execution/BuildManager.cs#L30-L38

### Question
Is this a NUKE issue or is there something wrong on my side?

Another note: when using `dotnet test` I don't experiencing the issues above. Here is the raw command:
```
.\dotCover.exe analyse
--ReportType=Html
--Output=D:\output\CodeCoverage\Report.dotCover.html
--TargetExecutable="C:\Program Files\dotnet\dotnet.exe"
--TargetArguments="test <list of test .dlls>"
--filter FullyQualifiedName!~IntegrationTest"
--InheritConsole=True
--AnalyseTargetArguments=True --Filters="<list of modules and methods to ignore>"
```

**Comment by chaquotay** [comment] 2021-01-13 13:00
Duplicate of #644

**Comment by Prodigio** [comment] 2021-01-13 13:03
Closed #644. The information provided here is the latest.

**Comment by Prodigio** [comment] 2021-01-13 14:16
A third way is this:
```
Logger.Warn("Load PresentationCore assembly the dirty way.");

var programFilesPath = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles);
var windowsDesktopAppPath = Path.Combine(programFilesPath, "dotnet", "shared", "Microsoft.WindowsDesktop.App");
var dllPath = Path.Combine(windowsDesktopAppPath, Environment.Version.ToString());
Logger.Info(dllPath);
var di = new DirectoryInfo(dllPath);
var files = di.GetFiles("PresentationCore.dll");
if (files.Length >= 1)
{
    var pcPath = Path.Combine(dllPath, files[0].Name);
    Assembly.LoadFrom(pcPath);
}
```
which loads the assembly, but still throws a
```
System.IO.FileNotFoundException : Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```
when the specific tests run.

**Comment by matkoch** [comment] 2021-01-13 14:28
@Prodigio have you read the contributions guidelines and issue template?

**Comment by Prodigio** [comment] 2021-01-13 14:34
@matkoch I did. Did I just miss to star nuke-build/nuke or is there something else I did wrong?


Well, I reconsidered the issue. If `dotnet test` is running fine, then the problem should be on NUnit side, not NUKE...

**Comment by matkoch** [comment] 2021-01-13 14:49
> Did you include the snippet of broken code in the issue?
> Did you verify it's not an external tool issue?

The template also mentions to include the relevant log output. I don't see any of that.

**Closed as completed** 2021-01-14 00:36 UTC
