### ISSUE TITLE
EnsureCleanDirectory deletes files in symlinked directories

### ISSUE THREAD

**Issue by MaxEden** [nuke-build/nuke#397] opened 2020-02-06 15:32 UTC
### Description
I have an output directory that contains some symlinked directories.
When I call EnsureCleanDirectory on top level directory, all the symlinked ones become wiped :)

### Expected
When I call EnsureCleanDirectory on top level directory, all symlinks unlinked, all files removed

I'm not really sure if current behavior is by design, and there are cases where proposed behavior is undesirable.

**Comment by matkoch** [comment] 2020-02-06 19:59
I'd say this is by design. You can iterate over the content instead, check whether the folder is symlink, and then delete or skip.

**Comment by MaxEden** [comment] 2020-02-07 14:51
Is there currently a way to check if directory is symlink that is platform-independent?

**Comment by matkoch** [comment] 2020-02-07 14:59
Not in nuke. Maybe in the BCL.

I hope it's okay if I close the issue for now.

**Closed as completed by matkoch** 2020-02-07 14:59 UTC
