### ISSUE TITLE
Can't disable logo via code

### ISSUE THREAD

**Issue by Nik4ant** [nuke-build/nuke#975] opened 2022-07-09 11:42 UTC
### Usage Information

Nuke 6.1.1; NET 6.0; Windows 10

### Description

There are multiple ways to disable logo: `EnableNoLogo()`, `SetNoLogo(true)` and `NoLogo = true;`. None of this works for some reason

### Reproduction Steps

1. Init nuke
2. Add Solution param: 
```csharp
[Solution] readonly Solution Solution;
```
3. Try to disable logo:
```csharp
Target Compile => _ => _
        .DependsOn(Restore)
        .Executes(() => {
            NoLogo = true;
            DotNetBuild(settings => settings
                .SetProjectFile(Solution)
                .EnableNoLogo()
                .SetNoLogo(true)
                );
        });
```

### Expected Behavior

No logo

### Actual Behavior

Logo still there

### Known Workarounds

Add `no-logo` param:
`nuke compile --no-logo`

**Comment by Nik4ant** [comment] 2022-07-09 12:00
I have read about [DisableDefaultOutputAttribute](https://github.com/nuke-build/nuke/pull/966#issue-1292097156), but I couldn't find it even after updating to `6.1.2`

**Comment by matkoch** [comment] 2022-07-09 12:02
It's very hard to understand which logo you mean – from NUKE or from .NET CLI. But in any case, everything is working as intended.

**Comment by matkoch** [comment] 2022-07-09 12:18
@Nik4ant obviously, the pull request was not yet merged.

**Closed as completed** 2022-07-09 12:18 UTC

**Comment by Nik4ant** [comment] 2022-07-09 13:09
> It's very hard to understand which logo you mean – from NUKE or from .NET CLI. But in any case, everything is working as intended.

I mean Nuke logo:
![image](https://user-images.githubusercontent.com/63895276/178107092-4596b941-1702-486a-af61-7671961b3461.png)
