### ISSUE TITLE
Nuke build senstive on line endings in build.cmd/build.sh/build.ps1 in azure pipeline

### ISSUE THREAD

**Issue by rafek1241** [nuke-build/nuke#768] opened 2021-07-14 09:29 UTC
### Usage Information

5.1.1

### Relevant Code / Invocations

```code
Just save build.cmd with CRLF endings and you will see issue on azure pipeline because of that when you will try unix agent.

:; set -eo pipefail
:; SCRIPT_DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
:; ${SCRIPT_DIR}/build.sh "$@"
:; exit $?
 
@ECHO OFF
powershell -ExecutionPolicy ByPass -NoProfile -File "%~dp0build.ps1" %*
```
```


### Expected Behavior

It should work regardless line endings.

### What actually happened?

_No response_

### Stacktrace / Log

```code
2021-07-14T09:20:03.5429732Z [command]/bin/bash --noprofile --norc /azp/agent/_work/_temp/0440e04c-6d8b-4449-9690-eee2f7ba422d.sh
2021-07-14T09:20:03.5503123Z ./build.cmd: line 1: set: pipefail
2021-07-14T09:20:03.5503486Z : invalid option name
2021-07-14T09:20:03.5515465Z ##[debug]Exit code 2 received from tool '/bin/bash'
2021-07-14T09:20:03.5522706Z ##[debug]STDIO streams have closed for tool '/bin/bash'
2021-07-14T09:20:03.5562160Z ##[error]Bash exited with code '2'.
2021-07-14T09:20:03.5570351Z ##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '2'.
2021-07-14T09:20:03.5571319Z ##[error]Bash wrote one or more lines to the standard error stream.
2021-07-14T09:20:03.5571998Z ##[debug]Processed: ##vso[task.issue type=error;]Bash wrote one or more lines to the standard error stream.
2021-07-14T09:20:03.5572789Z ##[error]./build.cmd: line 1: set: pipefail
: invalid option name
```

**Comment by rafek1241** [comment] 2021-07-14 09:30
Temporary workaround:
Change build.cmd/sh/ps1 line endings to `LF`.

**Comment by rafek1241** [comment] 2021-07-14 09:32
You can close that if you want, I just wanted you to be aware of something like this. It could be good to have at least FAQ documentation with cases like that.

**Comment by GeorgDangl** [comment] 2021-07-14 16:06
I've blogged about this: https://blog.dangl.me/archive/executing-nuke-build-scripts-on-linux-machines-with-correct-file-permissions/

I think that's been known for some time, but NUKE actually handles this. Both when you create a new project or `:update` an existing one, so ideally this should never happen.

I think it can become a problem when you manually change the `build.cmd` and `build.sh` scripts and your editor saves them with the wrong file endings, but you shouldn't do that😀

**Comment by GeorgDangl** [comment] 2021-07-14 16:07
I'm just closing the issue since I think it's handled already, and, as usual, there's much more to do than there is time available, but if you want @rafek1241, I think a PR with a new section in the FAQ would certainly be appreciated😀

**Closed as completed by GeorgDangl** 2021-07-14 16:06 UTC

**Comment by matkoch** [comment] 2021-07-14 16:09
I might be wrong, but AFAIR, this is the first time someone asked about it. So I don't think it's FAQ material.

**Comment by rafek1241** [comment] 2021-07-15 04:45
@GeorgDangl 
I took that from your blog post, actually :). NUKE does **not** handles it. I've created the nuke build through CLI (via nuke global tool) and I had CLRF in build execution files. Additionaly they were without `execute` permission. I didn't update `build.cmd/build.sh`.

@matkoch 
Okay 👍🏻.

**Comment by matkoch** [comment] 2021-07-15 19:06
It does handle execution flags:

https://github.com/nuke-build/nuke/blob/da06bf4ae348c5afb16fa5dc6b09c093c019cf28/source/Nuke.GlobalTool/Program.Setup.cs#L365

I have no idea what the issue is, but it seems to be on your end.

**Comment by GeorgDangl** [comment] 2021-07-15 20:32
You can also observe this behavior, when you initialize a new build, NUKE directly stages the script files. 

This might be a problem on Windows when you initialize NUKE before you set up your git repository, maybe that is what’s happening?
