### ISSUE TITLE
GitHub action using Ubuntu fails

### ISSUE THREAD

**Issue by sonomirco** [nuke-build/nuke#1426] opened 2024-09-22 07:01 UTC
### Usage Information

NUKE 8.0.0 / net8.0 / Windows

### Description

Using Ubuntu, I have permission denied by NUKE.

![image](https://github.com/user-attachments/assets/b2031886-e26c-4cb2-96d7-eaf634b99ff1)

As you can see from the image, the process doesn't even start.

### Reproduction Steps

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🏗 Run Nuke
        run: ./build.cmd

### Expected Behavior

Building Nuke as expected.

### Actual Behavior

I have a `permission denied` error.

### Could you help with a pull-request?

No

**Comment by lahma** [comment] 2024-09-22 08:22
Ubuntu is a Linux system, `build.cmd` is a Windows command. Use `build.sh` and ensure you have correct line endings in your repository.

**Comment by matkoch** [comment] 2024-09-22 09:12
@lahma `build.cmd` can work crossplatform

@sonomirco you've committed those files without execution permission. not a bug.

**Closed as not planned by matkoch** 2024-09-22 09:12 UTC
Labels: bug

**Comment by sonomirco** [comment] 2024-09-22 09:32
@matkoch
Are you talking about GitHub permissions? Because if I use Windows-latest build.cmd works without any permission request.

**Comment by matkoch** [comment] 2024-09-22 09:35
File execution permissions (`chmod +x`) on Git.

**Comment by sonomirco** [comment] 2024-09-22 09:51
Probably worth adding this to the documentation 😉.

https://blog.dangl.me/archive/executing-nuke-build-scripts-on-linux-machines-with-correct-file-permissions/

**Comment by matkoch** [comment] 2024-09-22 14:45
This issue is easy to find and is not specific to the project. 

https://github.com/orgs/community/discussions/26239

![2024-09-22-Arc-github actions permission denied-005082](https://github.com/user-attachments/assets/9f2aa042-dd4b-4d45-95ec-53874217e0a2)

Moreover, the setup does _exactly_ that. You must have made revert/reset operations after the setup.

**Comment by sonomirco** [comment] 2024-09-22 20:21
`Moreover, the setup does exactly that. You must have made revert/reset operations after the setup.`
No, I didn’t, but thanks for the information. 👍
